const IVTUsers = [
    '@ksenimiri',
    '@its1337fam',
    '@lsemikova',
    '@id227361380',
    '@denrax',
    '@neshko_artyom',
    '@berdenew',
    '@ell_rid',
    '@andreyast9',
    '@noadressherereally',
    '@epiccheesepie',
    '@id141105169',
    '@ishkenov',
    '@ymkach',
    '@mayer_one',
    '@kirillmoiseenkov',
    '@bestofoleg',
    '@id132265545',
    '@kapitan_kuchiki',
    '@fedo23nko',
    '@id32456525',
    '@ostey',
    '@le_paysan',
    '@megastick',
    '@d_plotnikova',
    '@mnasonov1998',
    '@johnpreaston',
    '@johnpreaston',
    '@afygentus',
    '@octodoctor',
    '@ademosh',
    '@v1k3n',
];

module.exports = IVTUsers;